// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package observer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INVALID-0]
	_ = x[START_SPAN-1]
	_ = x[FINISH_SPAN-2]
	_ = x[LOG_EVENT-3]
	_ = x[LOGF_EVENT-4]
	_ = x[SET_GAUGE-5]
	_ = x[ADD_GAUGE-6]
	_ = x[NEW_SCOPE-7]
	_ = x[NEW_MEASURE-8]
	_ = x[NEW_METRIC-9]
	_ = x[MODIFY_ATTR-10]
	_ = x[RECORD_STATS-11]
}

const _EventType_name = "INVALIDSTART_SPANFINISH_SPANLOG_EVENTLOGF_EVENTSET_GAUGEADD_GAUGENEW_SCOPENEW_MEASURENEW_METRICMODIFY_ATTRRECORD_STATS"

var _EventType_index = [...]uint8{0, 7, 17, 28, 37, 47, 56, 65, 74, 85, 95, 106, 118}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
